info:
  title: IIS Server
  description: The implementation of the IIS server.
  version: 1.0.0

openapi: 3.0.0

components:
  schemas:
    Role:
      type: string
      enum:
        - ADMIN
        - USER
    Privilege:
      type: string
      enum:
        - MANAGE_USERS
    User:
      type: object
      properties:
        id:
          type: integer
        username:
          type: string
        name:
          type: string
        role:
          $ref: '#/components/schemas/Role'
    Theme:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        description:
          type: string
    Campaign:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        themeId:
          type: integer
    CampaignStep:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
    CampaignStepFull:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        active:
          type: boolean
    PageInfo:
      type: object
      properties:
        index:
          type: integer
        size:
          type: integer
        totalPages:
          type: integer
  parameters:
    Id:
      name: id
      in: path
      required: true
      schema:
        type: integer
    PageIndex:
      name: pageIndex
      in: query
      required: true
      schema:
        type: integer
    PageSize:
      name: pageSize
      in: query
      required: true
      schema:
        type: integer
    Assigned:
      name: assigned
      in: query
      required: false
      schema:
        type: boolean
        description: Filter themes that are assigned to the current user.
  responses:
    JwtResponse:
      description: Used to return JWT token.
      content:
        application/json:
          schema:
            type: object
            properties:
              token:
                type: string

paths:
  /auth/login:
    post:
      summary: Login user.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/JwtResponse'
  /auth/register:
    post:
      summary: Register user.
      parameters:
        - name: createSession
          in: query
          required: false
          schema:
            type: boolean
            description: Whether to create a session upon registration.
            default: true
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
                name:
                  type: string
      responses:
        '200':
          $ref: '#/components/responses/JwtResponse'
  /auth/logout:
    post:
      summary: Logout user.
      responses:
        '200':
          description: Successfully logged out.
  /users:
    get:
      summary: Get all users.
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: List of users.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  page:
                    $ref: '#/components/schemas/PageInfo'

  /users/me:
    get:
      summary: Get current user.
      responses:
        '200':
          description: Current user information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
  /users/{id}:
    get:
      summary: Get user by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: User information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    delete:
      summary: Delete user by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: User deleted successfully.
        '403':
          description: Forbidden. Only ADMIN can delete users.
  /users/{id}/role:
    put:
      summary: Update user's role.
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                role:
                  $ref: '#/components/schemas/Role'
      responses:
        '200':
          description: User role updated successfully.
        '403':
          description: Forbidden. Only ADMIN can update user roles.
  /themes:
    post:
      summary: Create a new theme.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Theme created successfully.
        '403':
          description: Forbidden. Only ADMIN can create themes.
    delete:
      summary: Delete a theme.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Theme deleted successfully.
        '403':
          description: Forbidden. Only ADMIN can delete themes.
    get:
      summary: Get all themes.
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: List of themes.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Theme'
                  page:
                    $ref: '#/components/schemas/PageInfo'
  /themes/{id}:
    put:
      summary: Update theme by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                description:
                  type: string
      responses:
        '200':
          description: Theme updated successfully.
    get:
      summary: Get theme by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Theme information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
  /themes/{id}/inspect:
    get:
      summary: Inspect theme by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Theme deep information.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Theme'
  /campaigns:
    post:
      summary: Create a campaign.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                themeId:
                  type: integer
      responses:
        '200':
          description: Campaign created successfully.
    get:
      summary: Get campaigns by some criteria.
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Assigned'
        - name: themeId
          in: query
          required: false
          schema:
            type: integer
      description: If 'assigned' is true, returns only campaigns assigned to the current user. If 'themeId' is provided, filters campaigns by the specified theme ID.
      responses:
        '200':
          description: List of campaigns.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/Campaign'
                  page:
                    $ref: '#/components/schemas/PageInfo'
  /campaigns/{id}:
    delete:
      summary: Delete a campaign by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Campaign deleted successfully.
  /campaigns/{id}/inspect:
    get:
      summary: Inspect campaign by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Campaign deep information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  campaign:
                    $ref: '#/components/schemas/Campaign'
                  assignedUserId:
                    type: integer
                    description: The ID of the user assigned to this campaign, if any.
  /campaigns/{id}/steps:
    get:
      summary: Get steps of a campaign by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: List of campaign steps.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/CampaignStepFull'
  /campaigns/{id}/assign:
    post:
      summary: Assign a user to a campaign.
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        '200':
          description: Campaign assigned successfully.
  /steps:
    post:
      summary: Create a campaign step.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                campaignId:
                  type: integer
      responses:
        '200':
          description: Campaign step created successfully.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CampaignStep'
    get:
      summary: Get campaign steps by some criteria.
      parameters:
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/PageSize'
        - $ref: '#/components/parameters/Assigned'
      description: If 'assigned' is true, returns only steps assigned to the current user.
      responses:
        '200':
          description: List of campaign steps.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/CampaignStep'
                  page:
                    $ref: '#/components/schemas/PageInfo'
  /steps/{id}/inspect:
    get:
      summary: Inspect campaign step by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Campaign step deep information.
          content:
            application/json:
              schema:
                type: object
                properties:
                  campaign:
                    $ref: '#/components/schemas/Campaign'
                  assignedUserId:
                    type: integer
                    description: The ID of the user assigned to this step, if any.
                  accessPrivileges:
                    type: object
                    description: A map of privileges indicating whether the current user has access. (ASSIGN_STAFF)
                    additionalProperties:
                      type: boolean
  /steps/{id}/assign:
    post:
      summary: Assign a user to a campaign step.
      parameters:
        - $ref: '#/components/parameters/Id'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                userId:
                  type: integer
      responses:
        '200':
          description: Campaign step assigned successfully.
  /steps/{id}/activate:
    post:
      summary: Activate a campaign step by ID.
      parameters:
        - $ref: '#/components/parameters/Id'
      responses:
        '200':
          description: Campaign step activated successfully.
  /query/users:
    get:
      summary: Query users.
      parameters:
        - name: query
          in: query
          required: true
          schema:
            type: string
        - $ref: '#/components/parameters/PageIndex'
        - $ref: '#/components/parameters/PageSize'
      responses:
        '200':
          description: List of users matching the query.
          content:
            application/json:
              schema:
                type: object
                properties:
                  items:
                    type: array
                    items:
                      $ref: '#/components/schemas/User'
                  page:
                    $ref: '#/components/schemas/PageInfo'